# Generated by Django 3.1.4 on 2021-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210112_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='storage_drive',
            field=models.ImageField(blank=True, null=True, upload_to='drive'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='article/thumbnail'),
        ),
    ]
