# Generated by Django 3.1.4 on 2021-01-14 04:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210112_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='storage_drive',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
