# Generated by Django 3.1.4 on 2021-01-16 01:34

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210114_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
